language: ruby
script: bundle exec jekyll build
after_success: touch _site/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  repo: skyqrose/skyqrose.github.io
  target_branch: master
  local_dir: _site/
  keep_history: true
  allow_empty_commit: true
  github_token: $GITHUB_TOKEN # set on travis-ci.com
